spring.application.name=notification-service
server.port=8085

mail.retry.fixedRate=300000
mail.retry.maxAttempts=5
mail.adminMail=yuliia.v.kushnir@gmail.com

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.service-name=${spring.application.name}

# Elasticsearch connection
spring.elasticsearch.uris=http://elasticsearch:9200
spring.elasticsearch.username=
spring.elasticsearch.password=

# SMTP connection
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.health.show-details=always
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=*
management.health.elasticsearch.enabled=false